PLAYING WITH 1ST COMBINED DATASET

In [24]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('HkiCyclistsandWeather_2016_2018_ver20200324.csv')

# What has to be done for e.g. Month, Year, Rush Hours, Weekend, Morning/evening

In [25]:
df.head()
# where does the "Unnamed: 0" come from?

,Unnamed: 0,Date,Time,Weekday,RelativeHumidity(%),AirTemperature(degC),SnowDepth(cm),WindSpeed(m/s),WindDirection(deg),Auroransilta,...,Merikannontie,Munkkiniemi bridge south side,Munkkiniemi bridge north side,Heperia park/Ooppera,Pitkasilta itapuoli,Pitkasilta west side,Lauttasaari bridge north side,Ratapihantie,Viikintie,Baana
0,0,2016-01-01,00:00,Fri,81.0,-3.5,0.0,4.3,164.0,NaN,...,2.0,3.0,2.0,11.0,7.0,11.0,3.0,2.0,NaN,6.0
1,1,2016-01-01,01:00,Fri,78.0,-3.5,0.0,4.1,144.0,NaN,...,1.0,0.0,1.0,1.0,4.0,6.0,4.0,10.0,NaN,5.0
2,2,2016-01-01,02:00,Fri,78.0,-3.3,0.0,5.0,173.0,NaN,...,2.0,1.0,3.0,6.0,6.0,12.0,5.0,2.0,NaN,5.0
3,3,2016-01-01,03:00,Fri,78.0,-3.0,0.0,3.9,147.0,NaN,...,1.0,0.0,1.0,4.0,4.0,3.0,0.0,7.0,NaN,3.0
4,4,2016-01-01,04:00,Fri,76.0,-3.5,0.0,3.4,144.0,NaN,...,3.0,2.0,2.0,6.0,2.0,11.0,0.0,1.0,NaN,3.0

In [26]:
df.tail()

,Unnamed: 0,Date,Time,Weekday,RelativeHumidity(%),AirTemperature(degC),SnowDepth(cm),WindSpeed(m/s),WindDirection(deg),Auroransilta,...,Merikannontie,Munkkiniemi bridge south side,Munkkiniemi bridge north side,Heperia park/Ooppera,Pitkasilta itapuoli,Pitkasilta west side,Lauttasaari bridge north side,Ratapihantie,Viikintie,Baana
26300,26300,2018-12-31,20:00,Mon,91.0,1.0,0.0,8.8,207.0,1.0,...,2.0,3.0,0.0,11.0,6.0,8.0,NaN,7.0,NaN,9.0
26301,26301,2018-12-31,21:00,Mon,88.0,1.3,0.0,9.5,207.0,1.0,...,7.0,5.0,0.0,5.0,1.0,2.0,NaN,10.0,NaN,5.0
26302,26302,2018-12-31,22:00,Mon,95.0,0.8,0.0,7.6,200.0,1.0,...,0.0,0.0,0.0,7.0,5.0,5.0,NaN,8.0,NaN,7.0
26303,26303,2018-12-31,23:00,Mon,95.0,1.1,2.0,8.6,204.0,3.0,...,0.0,1.0,1.0,7.0,5.0,8.0,NaN,1.0,NaN,2.0
26304,26304,2019-01-01,00:00,NaN,94.0,1.4,2.0,8.4,207.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#Set Indexes
#df = df.set_index(['Date','Time'])
#df.head()

In [28]:
df.info()
# a lot of missing data in Auroransilta, Kaivokatu, Kapyla pohjois..., Viikintie, LAuttasaari North

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26305 entries, 0 to 26304
Data columns (total 29 columns):
Unnamed: 0                        26305 non-null int64
Date                              26305 non-null object
Time                              26305 non-null object
Weekday                           26304 non-null object
RelativeHumidity(%)               26274 non-null float64
AirTemperature(degC)              26303 non-null float64
SnowDepth(cm)                     26221 non-null float64
WindSpeed(m/s)                    26069 non-null float64
WindDirection(deg)                26070 non-null float64
Auroransilta                      10010 non-null float64
Etelaesplanadi                    26280 non-null float64
Huopalahti (station)              26304 non-null float64
Kaisaniemi/Elaintarhanlahti       26304 non-null float64
Kaivokatu                         10008 non-null float64
Kulosaari bridge south            26304 non-null float64
Kulosaaren silta po.              26304 non-null float64
Kuusisaarentie                    26304 non-null float64
Kapyla, Pohjoisbaana              11445 non-null float64
Lauttasaarin bridge south side    26304 non-null float64
Merikannontie                     26304 non-null float64
Munkkiniemi bridge south side     26304 non-null float64
Munkkiniemi bridge north side     26304 non-null float64
Heperia park/Ooppera              26304 non-null float64
Pitkasilta itapuoli               26304 non-null float64
Pitkasilta west side              26304 non-null float64
Lauttasaari bridge north side     24944 non-null float64
Ratapihantie                      26304 non-null float64
Viikintie                         9169 non-null float64
Baana                             26304 non-null float64
dtypes: float64(25), int64(1), object(3)
memory usage: 5.8+ MB

In [29]:
df = df.drop(['Unnamed: 0','Auroransilta', 'Kaivokatu', 'Kapyla, Pohjoisbaana', 'Lauttasaari bridge north side', 'Viikintie'], axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26305 entries, 0 to 26304
Data columns (total 23 columns):
Date                              26305 non-null object
Time                              26305 non-null object
Weekday                           26304 non-null object
RelativeHumidity(%)               26274 non-null float64
AirTemperature(degC)              26303 non-null float64
SnowDepth(cm)                     26221 non-null float64
WindSpeed(m/s)                    26069 non-null float64
WindDirection(deg)                26070 non-null float64
Etelaesplanadi                    26280 non-null float64
Huopalahti (station)              26304 non-null float64
Kaisaniemi/Elaintarhanlahti       26304 non-null float64
Kulosaari bridge south            26304 non-null float64
Kulosaaren silta po.              26304 non-null float64
Kuusisaarentie                    26304 non-null float64
Lauttasaarin bridge south side    26304 non-null float64
Merikannontie                     26304 non-null float64
Munkkiniemi bridge south side     26304 non-null float64
Munkkiniemi bridge north side     26304 non-null float64
Heperia park/Ooppera              26304 non-null float64
Pitkasilta itapuoli               26304 non-null float64
Pitkasilta west side              26304 non-null float64
Ratapihantie                      26304 non-null float64
Baana                             26304 non-null float64
dtypes: float64(20), object(3)
memory usage: 4.6+ MB

In [41]:
# Snow depth corrections
# case['location'] = np.where(case.prov_state.isnull(), case.country, case.prov_state)
df['SnowDepth(cm)'] = np.where(df['SnowDepth(cm)'].isnull(), 0.0, df['SnowDepth(cm)'])
df.loc[273:325,'SnowDepth(cm)'] = 23.0
df.loc[425:427,'SnowDepth(cm)'] = 22.0
df.loc[560:622,'SnowDepth(cm)'] = 22.0
df.loc[19151:19211,'SnowDepth(cm)'] = 23.0
df.loc[19742:19761,'SnowDepth(cm)'] = 23.0

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26305 entries, 0 to 26304
Data columns (total 24 columns):
index                             26305 non-null int64
Date                              26305 non-null object
Time                              26305 non-null object
Weekday                           26304 non-null object
RelativeHumidity(%)               26274 non-null float64
AirTemperature(degC)              26303 non-null float64
SnowDepth(cm)                     26305 non-null float64
WindSpeed(m/s)                    26069 non-null float64
WindDirection(deg)                26070 non-null float64
Etelaesplanadi                    26280 non-null float64
Huopalahti (station)              26304 non-null float64
Kaisaniemi/Elaintarhanlahti       26304 non-null float64
Kulosaari bridge south            26304 non-null float64
Kulosaaren silta po.              26304 non-null float64
Kuusisaarentie                    26304 non-null float64
Lauttasaarin bridge south side    26304 non-null float64
Merikannontie                     26304 non-null float64
Munkkiniemi bridge south side     26304 non-null float64
Munkkiniemi bridge north side     26304 non-null float64
Heperia park/Ooppera              26304 non-null float64
Pitkasilta itapuoli               26304 non-null float64
Pitkasilta west side              26304 non-null float64
Ratapihantie                      26304 non-null float64
Baana                             26304 non-null float64
dtypes: float64(20), int64(1), object(3)
memory usage: 4.8+ MB

In [43]:
df.describe()

,index,RelativeHumidity(%),AirTemperature(degC),SnowDepth(cm),WindSpeed(m/s),WindDirection(deg),Etelaesplanadi,Huopalahti (station),Kaisaniemi/Elaintarhanlahti,Kulosaari bridge south,...,Kuusisaarentie,Lauttasaarin bridge south side,Merikannontie,Munkkiniemi bridge south side,Munkkiniemi bridge north side,Heperia park/Ooppera,Pitkasilta itapuoli,Pitkasilta west side,Ratapihantie,Baana
count,26305.000000,26274.000000,26303.000000,26305.000000,26069.000000,26070.000000,26280.000000,26304.000000,26304.000000,26304.000000,...,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000,26304.000000
mean,13152.000000,78.844104,6.890195,1.609580,3.491699,201.141082,52.157953,47.091735,47.609907,4.092001,...,44.514713,92.838998,76.669632,46.350555,28.984375,103.557330,72.580026,38.393894,49.951262,101.274293
std,7593.743752,15.633415,8.725958,5.309879,1.575847,100.700415,68.488112,73.634712,65.554367,13.808725,...,68.011190,119.252479,106.428303,68.867400,40.136455,144.560935,93.977022,42.300716,73.500443,136.121898
min,0.000000,19.000000,-23.800000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6576.000000,70.000000,0.700000,-1.000000,2.400000,117.000000,5.000000,4.000000,4.000000,0.000000,...,3.000000,9.000000,5.000000,4.000000,3.000000,10.000000,8.000000,7.000000,6.000000,10.000000
50%,13152.000000,83.000000,6.000000,0.000000,3.300000,222.000000,23.000000,18.000000,20.000000,0.000000,...,15.000000,42.000000,28.000000,17.000000,13.000000,41.000000,32.000000,21.000000,22.000000,41.000000
75%,19728.000000,91.000000,14.300000,0.000000,4.400000,283.000000,75.000000,57.000000,67.000000,0.000000,...,58.250000,136.000000,107.000000,61.000000,41.000000,143.000000,104.000000,57.000000,61.000000,146.000000
max,26304.000000,100.000000,30.200000,23.000000,12.400000,360.000000,481.000000,688.000000,504.000000,244.000000,...,546.000000,950.000000,731.000000,498.000000,493.000000,1153.000000,678.000000,260.000000,655.000000,863.000000

In [33]:
# [[Etelaesplanadi',
#       'Huopalahti (station)', 'Kaisaniemi/Elaintarhanlahti',
 #      'Kulosaari bridge south', 'Kulosaaren silta po. ', 'Kuusisaarentie',
  #     'Lauttasaarin bridge south side',
   #    'Merikannontie', 'Munkkiniemi bridge south side',
    #   'Munkkiniemi bridge north side', 'Heperia park/Ooppera',
     #  'Pitkasilta itapuoli', 'Pitkasilta west side',
      #  'Ratapihantie', 'Baana']]

In [34]:

samplea = df[['AirTemperature(degC)', 'RelativeHumidity(%)','WindSpeed(m/s)','Etelaesplanadi', 'Kuusisaarentie','Merikannontie','Ratapihantie', 'Baana']]
samplea.head()

,AirTemperature(degC),RelativeHumidity(%),WindSpeed(m/s),Etelaesplanadi,Kuusisaarentie,Merikannontie,Ratapihantie,Baana
0,-3.5,81.0,4.3,12.0,1.0,2.0,2.0,6.0
1,-3.5,78.0,4.1,3.0,0.0,1.0,10.0,5.0
2,-3.3,78.0,5.0,5.0,0.0,2.0,2.0,5.0
3,-3.0,78.0,3.9,3.0,1.0,1.0,7.0,3.0
4,-3.5,76.0,3.4,3.0,1.0,3.0,1.0,3.0

In [35]:
#sns.pairplot(samplea)

In [36]:
#sns.set(rc={'figure.figsize':(11.7,8.27)})
#sns.barplot(data=samplea)

In [44]:
# reset index
df = df.reset_index()
df.head()

,level_0,index,Date,Time,Weekday,RelativeHumidity(%),AirTemperature(degC),SnowDepth(cm),WindSpeed(m/s),WindDirection(deg),...,Kuusisaarentie,Lauttasaarin bridge south side,Merikannontie,Munkkiniemi bridge south side,Munkkiniemi bridge north side,Heperia park/Ooppera,Pitkasilta itapuoli,Pitkasilta west side,Ratapihantie,Baana
0,0,0,2016-01-01,00:00,Fri,81.0,-3.5,0.0,4.3,164.0,...,1.0,4.0,2.0,3.0,2.0,11.0,7.0,11.0,2.0,6.0
1,1,1,2016-01-01,01:00,Fri,78.0,-3.5,0.0,4.1,144.0,...,0.0,0.0,1.0,0.0,1.0,1.0,4.0,6.0,10.0,5.0
2,2,2,2016-01-01,02:00,Fri,78.0,-3.3,0.0,5.0,173.0,...,0.0,5.0,2.0,1.0,3.0,6.0,6.0,12.0,2.0,5.0
3,3,3,2016-01-01,03:00,Fri,78.0,-3.0,0.0,3.9,147.0,...,1.0,2.0,1.0,0.0,1.0,4.0,4.0,3.0,7.0,3.0
4,4,4,2016-01-01,04:00,Fri,76.0,-3.5,0.0,3.4,144.0,...,1.0,3.0,3.0,2.0,2.0,6.0,2.0,11.0,1.0,3.0

In [38]:
#sns.boxplot(x='Etelaesplanadi', data = samplea)
#sns.boxplot(data = samplea)

In [39]:
#sns.lineplot()

In [45]:
df.to_csv('HkiCyclistsandWeather_2016_2018_cleaned_ver20200324.csv')