# Espoo part of cyclists

In [80]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [81]:
#
# Chech file name before execute this command, just in case
#
ESPOO_bikers = pd.read_excel('Espoon_pyorailijamaarat.xlsx')
ESPOO_bikerstation = pd.read_excel('Espoo_pyoralaskentapisteiden_sijainnit.xlsx')

In [82]:
# print out dataset
ESPOO_bikers

,Päivä,Päivämäärä,Aika,Espoon portti (Eco-Counter),Espoonlahdenraitti (Eco-Counter),Gallen-Kallela (Eco-Counter),Gallen-Kallelan tie (DSL10),Haukilahti (Viacount),Kalevalantien alikulku (DSL10),"Kehä I, Laajalahti (DSL10)",...,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135
0,pe,2014-01-03,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,pe,2014-01-03,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,pe,2014-01-03,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,pe,2014-01-03,03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
4,pe,2014-01-03,04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38011,NaN,2019-05-13,19:00:00,69.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
38012,NaN,2019-05-13,20:00:00,76.0,NaN,54.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
38013,NaN,2019-05-13,21:00:00,46.0,NaN,25.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
38014,NaN,2019-05-13,22:00:00,25.0,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
38015,NaN,2019-05-13,23:00:00,25.0,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [83]:
# print out dataset
ESPOO_bikerstation

                                        Nimi        P         I
0                Espoon portti (eco-counter)  6677005  25481128
1           Espoonlahdenraitti (Eco-counter)  6670508  25481015
2               Gallen-Kallela (Eco-counter)  6676933  25491239
3                        Gallen-Kallelan tie  6676982  25491205
4                                 Haukilahti  6671287  25487507
5                     Kalevalantien alikulku  6674496  25488788
6                         Kehä I, Laajalahti  6675867  25489239
7           Kehä I, Laajalahti (Eco-counter)  6675822  25489228
8                   Keilaniemi, Keilaterassi  6673117  25490525
9                   Keskuspuisto, etelähaara  6674356  25483281
10             Keskuspuisto, etelähaara, itä  6674246  25483392
11           Keskuspuisto, etelähaara, länsi  6674139  25483318
12                   Keskuspuisto, Grimängen  6675139  25482600
13                   Keskuspuisto, Mössenkär  6675346  25482598
14                                Kiltapolku  6676648  25481080
15                        Kiltaraitti, etelä  6676640  25481048
16                    Kiltaraitti, pohjoinen  6676731  25481014
17                           Kirkkojärventie  6677166  25481274
18                     Kivenlahden uimaranta  6670997  25479610
19                                Kivenlahti  6671256  25479244
20                  Länsiväylä (Eco-counter)  6676933  25491239
21                    Länsiväylä, Karhusaari  6672835  25490802
22                           Martinsillantie  6671916  25482907
23                             Merituulentie  6673128  25486530
24                 Olarinkatu (Eco-counter)   6673083  25485174
25                                  Otaniemi  6674433  25490910
26                            Pitkäjärventie  6682359  25487568
27                       Pohjantien ylikulku  6673592  25488943
28   Päivänkestämönpolku, Kera (eco-counter)  6678235  25486566
29          Rantaradanraitti, Helsingin raja  6679003  25491669
30                                    Soukka  6668766  25481315
31             Suomenlahdentie (Eco-counter)  6671530  25484766
32   Suomenlahdentie (pohjoinen & eteläinen)  6671545  25484748
33    Tapiola, Länsituulenkuja (eco-counter)  6673578  25488895
34  Turuntie, Rantaradanreitti (eco-counter)  6678976  25491608
35            Vihdintie, Kalajärven itäpuoli  6688155  25485793
36                        Vihdintie, Uusmäki  6682147  25490666
37      Ylismäentie, Suurpelto (eco-counter)  6674318  25485946

In [84]:
#
# drop unnamed columns away, those columns are all empty
#
i = 43
for x in range(len(ESPOO_bikers.columns)-43):
    name = 'Unnamed: {}'.format(i)
    ESPOO_bikers = ESPOO_bikers.drop([name], axis=1)
    i += 1

In [85]:
# print out dataset
ESPOO_bikers

,Päivä,Päivämäärä,Aika,Espoon portti (Eco-Counter),Espoonlahdenraitti (Eco-Counter),Gallen-Kallela (Eco-Counter),Gallen-Kallelan tie (DSL10),Haukilahti (Viacount),Kalevalantien alikulku (DSL10),"Kehä I, Laajalahti (DSL10)",...,"Rantaradanraitti, Helsingin raja (Viacount 2)",Soukka (Viacount),Suomenlahdentie (Eco-Counter),"Suomenlahdentie, eteläinen (viacount)","Suomenlahdentie, pohjoinen (Viacount)","Tapiola,Länsituulenkuja (Eco-Counter)","Turuntie, Rantaradanreitti (Eco-Counter)","Vihdintie, Kalajärven itäpuoli (Viacount 2)","Vihdintie, Uusmäki (DSL10)","Ylismäentie,Suurpelto (Eco-Counter)"
0,pe,2014-01-03,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pe,2014-01-03,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pe,2014-01-03,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pe,2014-01-03,03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pe,2014-01-03,04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38011,NaN,2019-05-13,19:00:00,69.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,19.0,NaN,NaN,NaN,50.0,NaN,NaN,40.0
38012,NaN,2019-05-13,20:00:00,76.0,NaN,54.0,NaN,NaN,NaN,NaN,...,NaN,NaN,23.0,NaN,NaN,NaN,27.0,NaN,NaN,41.0
38013,NaN,2019-05-13,21:00:00,46.0,NaN,25.0,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,10.0,NaN,NaN,22.0
38014,NaN,2019-05-13,22:00:00,25.0,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,6.0,NaN,NaN,7.0
38015,NaN,2019-05-13,23:00:00,25.0,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,3.0,NaN,NaN,7.0

In [86]:
# rename columns' column names, change ä -> a and ö -> o
ESPOO_bikers = ESPOO_bikers.rename({'Päivä': 'Weekday', 'Päivämäärä': 'Date', 'Aika':'Time', 'Keskuspuisto, etelähaara, itä (Viacount 2)': 'Keskuspuisto, etelahaara, ita (Viacount 2)', 'Keskuspuisto, etelähaara, länsi (Viacount 2)': 'Keskuspuisto, etelahaara, lansi (Viacount 2)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Keskuspuisto, Grimängen (Viacount 2)': 'Keskuspuisto, Grimangen (Viacount 2)', 'Keskuspuisto, Mössenkär (Viacount 2)': 'Keskuspuisto, Mossenkar (Viacount 2)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Kiltaraitti, etelä (Viacount 2)': 'Kiltaraitti, etela (Viacount 2)', 'Kirkkojärventie (DSL10)': 'Kirkkojarventie (DSL10)', 'Länsiväylä (Eco-counter)': 'Lansivayla (Eco-counter)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Länsiväylä, Karhusaari (DSL10)': 'Lansivayla, Karhusaari (DSL10)', 'Pitkäjärventie (DSL10)': 'Pitkajarventie (DSL10)', 'Päivänkestämönpolku, Kera (Eco-Counter)': 'Paivankestamonpolku, Kera (Eco-Counter)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Suomenlahdentie, eteläinen (viacount)': 'Suomenlahdentie, etelainen (viacount)', 'Tapiola,Länsituulenkuja (Eco-Counter)': 'Tapiola,Lansituulenkuja (Eco-Counter)', 'Vihdintie, Kalajärven itäpuoli (Viacount 2)': 'Vihdintie, Kalajarven itapuoli (Viacount 2)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Vihdintie, Uusmäki (DSL10)': 'Vihdintie, Uusmaki (DSL10)', 'Ylismäentie,Suurpelto (Eco-Counter)': 'Ylismaentie,Suurpelto (Eco-Counter)'}, axis=1)
ESPOO_bikers = ESPOO_bikers.rename({'Kehä I, Laajalahti (DSL10)': 'Keha I, Laajalahti (DSL10)', 'Kehä I, Laajalahti (Eco-counter)': 'Keha I, Laajalahti (Eco-counter)'}, axis=1)
ESPOO_bikers

,Weekday,Date,Time,Espoon portti (Eco-Counter),Espoonlahdenraitti (Eco-Counter),Gallen-Kallela (Eco-Counter),Gallen-Kallelan tie (DSL10),Haukilahti (Viacount),Kalevalantien alikulku (DSL10),"Keha I, Laajalahti (DSL10)",...,"Rantaradanraitti, Helsingin raja (Viacount 2)",Soukka (Viacount),Suomenlahdentie (Eco-Counter),"Suomenlahdentie, etelainen (viacount)","Suomenlahdentie, pohjoinen (Viacount)","Tapiola,Lansituulenkuja (Eco-Counter)","Turuntie, Rantaradanreitti (Eco-Counter)","Vihdintie, Kalajarven itapuoli (Viacount 2)","Vihdintie, Uusmaki (DSL10)","Ylismaentie,Suurpelto (Eco-Counter)"
0,pe,2014-01-03,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,pe,2014-01-03,01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,pe,2014-01-03,02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pe,2014-01-03,03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pe,2014-01-03,04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38011,NaN,2019-05-13,19:00:00,69.0,NaN,56.0,NaN,NaN,NaN,NaN,...,NaN,NaN,19.0,NaN,NaN,NaN,50.0,NaN,NaN,40.0
38012,NaN,2019-05-13,20:00:00,76.0,NaN,54.0,NaN,NaN,NaN,NaN,...,NaN,NaN,23.0,NaN,NaN,NaN,27.0,NaN,NaN,41.0
38013,NaN,2019-05-13,21:00:00,46.0,NaN,25.0,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,10.0,NaN,NaN,22.0
38014,NaN,2019-05-13,22:00:00,25.0,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,6.0,NaN,NaN,NaN,6.0,NaN,NaN,7.0
38015,NaN,2019-05-13,23:00:00,25.0,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,3.0,NaN,NaN,7.0

In [87]:
#
# replace finnish word with english words due to datetime convertion
#
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('ma', 'Mon')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('ti', 'Tue')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('ke', 'Wed')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('to', 'Thu')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('pe', 'Fri')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('la', 'Sat')
ESPOO_bikers.Weekday = ESPOO_bikers.Weekday.str.replace('su', 'Sun')
# print put result
ESPOO_bikers=ESPOO_bikers.set_index('Date')
weekdaystr=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
ESPOO_bikers.Weekday=np.array([weekdaystr[date.weekday()] for date in ESPOO_bikers.index.date])

ESPOO_bikers

AttributeError: 'RangeIndex' object has no attribute 'date'

In [79]:
ESPOO_bikers.Weekday=np.array([weekdaystr[date.weekday()] for date in ESPOO_bikers.index.date])

ESPOO_bikers

AttributeError: 'RangeIndex' object has no attribute 'date'

### write cleaned data into excel csv file

In [10]:
ESPOO_bikers.to_csv(r'C:\Users\katar\Documents\Tyovoimakoulutus\Python_FEC_2020\FinalProject\CityBikes\EspooBikers_cleanDataset.csv', index = False)